spring:
  application:
    name: pt-pass-batch
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&serverTimezone=Asia/Seoul
    username: batch_user
    password: Root123!@asd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: "SELECT 1"
      minimum-idle: 10
      maximum-pool-size: 200
  batch:
    job:
      enabled: false # true : Spring Boot 실행시 등록된 Job 실행.
      name: addPassesJob
    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 실행합니다. 임베디드인 경우에는 기본적으로 실행하는데, always 설정을 하면 임베디드 타입처럼 항상 활성화시킬 수 있습니다.
      # 초기 수행한 이후에는 꺼두어도 됩니다.
      initialize-schema: always


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션

  sql.init.mode: always