spring:
  application:
    name: pt-pass-batch
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pass_local?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&serverTimezone=Asia/Seoul
    username: batch_user
    password: Root123!@asd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: "SELECT 1"
      minimum-idle: 10
      maximum-pool-size: 200
  batch:
    job:
      enabled: false # true : Spring Boot 실행시 등록된 Job 실행.
      name: addPassesJob, expirePassJob # 실제 사용할 job 설정
    jdbc:
      # Batch 에 사용 되는 SQL 초기화 script 실행.
      # 초기 수행 이후 꺼도 됩니다.
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션

  sql.init.mode: always