version: "3.8"
services:
  mysql:
    container_name: mysql_local_db
    image: mysql:8.0
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=batch_user
      - MYSQL_PASSWORD=Root123!@asd
      - MYSQL_ROOT_PASSWORD=Root123!@asd
      - TZ=Asia/Seoul
    restart: always